#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

~/.screenlayout/dual_monitor.sh

bspc monitor eDP-1-1 -d       7 8 
bspc monitor HDMI-1-1 -d 󱧐


bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config top_monocle_padding 8
bspc config focused_border_color '#957FB8'

#seting layouts for specific workspaces
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 󱧐
bsp-layout set monocle 8

bsp-layout set tall 
bsp-layout set tall 
bsp-layout set tall 7

#window rules
#run "xprop | grep WM_CLASS" to find window class
bspc rule -a 'discord' desktop=''
bspc rule -a 'Spotify' desktop=''
bspc rule -a 'VirtualBox Machine' desktop='8'
bspc rule -a 'VirtualBox Manager' desktop='8'
bspc rule -a 'Gnome-calculator' state=floating
bspc rule -a 'Xmessage' state=floating

discord &

/home/utilizador/.config/bspwm/startup.sh

betterlockscreen -u $image --fx & #only renders normal image
