#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc rule -r "*"

xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --mode 1080x2160 --pos 0x1080 --rotate right --output HDMI-2 --off

bspc wm -O eDP-1 HDMI-1

bspc monitor eDP-1 -d   󰈙      
bspc monitor HDMI-1 -d 󱧐

~/.config/bspwm/set_wallpaper.sh

bspc config -m eDP-1 top_monocle_padding 0
bspc config -m HDMI-1 top_monocle_padding 8

bspc config border_width         4
bspc config window_gap           8

bspc config focused_border_color '#957FB8'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

# ~/bin/single_monitor.sh

#seting layouts for specific workspaces
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 
bsp-layout set monocle 󱧐
bsp-layout set monocle 

bsp-layout set tall 󰈙
bsp-layout set tall 
bsp-layout set tall 
bsp-layout set tall 

#window rules
#run "xprop | grep WM_CLASS" to find window class
bspc rule -a 'discord' desktop='' follow=true

bspc rule -a 'Spotify' desktop='' follow=true

bspc rule -a 'VirtualBox Machine' desktop='' follow=true
bspc rule -a 'VirtualBox Manager' desktop='' follow=true

bspc rule -a 'Evince' desktop='󰈙' follow=true
bspc rule -a 'Zathura' desktop='󰈙' follow=true
bspc rule -a 'Shotwell' desktop='󰈙' follow=true
bspc rule -a 'sioyek' desktop='󰈙' follow=true
bspc rule -a 'matplotlib' desktop='󰈙' follow=true

bspc rule -a 'Org.gnome.Nautilus' desktop='' follow=true

bspc rule -a 'Youtube' desktop='' follow=true
bspc rule -a 'Firefox' desktop='' follow=true

bspc rule -a 'Gnome-calculator' state=floating
bspc rule -a 'Float' state=floating follow=off
bspc rule -a 'Xmessage' state=floating
bspc rule -a 'Gnome-control-center' state=floating
bspc rule -a 'Zathura' state=tiled

/home/utilizador/.config/bspwm/startup.sh


