#!/bin/bash

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
exec polybar example --config=~/.config/polybar/workspaces.ini &
exec polybar example --config=~/.config/polybar/icons.ini &
exec polybar example --config=~/.config/polybar/utilities.ini &
exec polybar example --config=~/.config/polybar/clock.ini &

